name: Install Static Qt
description: Install the static build of Qt
runs:
  using: "composite"
  steps:
    - name: Install Static Qt
      shell: bash
      run: |
        os_name=""
        case "${{ runner.os }}" in
          Linux)   echo "Linux not supported"; exit 1 ;;
          macOS)   os_name=macos ;;
          Windows) [ "${{ runner.arch }}" = "ARM64" ] && os_name=windows-arm || os_name=windows ;;
          *)       echo "Unknown OS"; exit 1 ;;
        esac
        qt_version=${VERSION_TAG#*v}
        qt_version=${qt_version%-*}
        curl -LO https://github.com/AllanChain/install-qt-static/releases/download/${VERSION_TAG}/qt-${qt_version}-static-${os_name}.zip
        7z x qt-*.zip
        if [[ $os_name == windows* ]]; then
          echo "$(pwd -W | sed 's,/,\\,g')\qt_static\bin" >> $GITHUB_PATH
        else
          echo "$(pwd)/qt_static/bin" >> $GITHUB_PATH
        fi
      env:
        VERSION_TAG: v6.9.2-2
