name: Build static Qt

on: push

env:
  QT6_VERSION: 6.7.2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        include:
        - os: windows-latest
          os-caption: windows
        - os: macos-latest
          os-caption: macos

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
    - name: Clone Qt6 repo
      run: |
        git clone https://code.qt.io/qt/qt5.git qt6 -b '${{env.QT6_VERSION}}'
        cd qt6
        perl init-repository -f --module-subset=qtbase,qtdeclarative,qttranslations,qtimageformats,qtsvg

    - name: Build Qt6 (Windows)
      if: contains(matrix.os, 'windows')
      shell: cmd
      run: |
        mkdir qt6_build
        cd qt6_build
        "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvarsall.bat" amd64
        ..\qt6\configure.bat -release -static -optimize-size -prefix "..\qt6_static_64" -no-feature-accessibility
        cmake --build . --parallel 4
        cmake --install .

    - name: Build Qt6 (macOS)
      if: contains(matrix.os, 'macos')
      run: |
        mkdir qt6_build
        cd qt6_build
        ../qt6/configure -static -release -optimize-size -prefix "../qt6_static_64" -no-feature-accessibility -- -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        cmake --build . --parallel 3
        cmake --install .

    - name: Package binaries
      run: |
        7z a qt6_static_64.zip qt6_static_64

    - uses: actions/upload-artifact@v1
      with:
        name: "qt6_static_${{matrix.os-caption}}"
        path: qt6_static_64.zip
